import {env} from 'cloudflare:workers';
import {headers} from 'next/headers';
import {getAddress,isAddress,verifyMessage,type Hex} from 'viem';
import {createSiweMessage} from 'viem/siwe';
const sessionCookie='tg_wallet_session',challengeCookie='tg_wallet_challenge';
const bucket=()=> (env as unknown as {BUCKET:R2Bucket}).BUCKET;
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
async function key(token:string){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));return Array.from(new Uint8Array(h),b=>b.toString(16).padStart(2,'0')).join('')}
function cookieValue(value:string|null,name:string){return value?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)}
function cookie(name:string,value:string,req:Request,age:number){return `${name}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${age}${new URL(req.url).protocol==='https:'?'; Secure':''}`}
function originCheck(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)throw new Error('Cross-origin action rejected.')}
export async function walletUser(req?:Request){const token=cookieValue((req?.headers??await headers()).get('cookie'),sessionCookie);if(!token||!/^\w{64}$/.test(token))return null;const record=await bucket().get('auth/session/'+await key(token));if(!record)return null;const data=await record.json<{address:string;expires:number}>();if(data.expires<=Date.now())return null;return {userId:'wallet:'+data.address.toLowerCase(),displayName:data.address.slice(0,6)+'…'+data.address.slice(-4)};}
export async function challenge(req:Request){originCheck(req);const body=await req.json() as {address?:string;chainId?:number};if(!body.address||!isAddress(body.address))throw new Error('Invalid wallet address.');if(body.chainId!==undefined&&(!Number.isSafeInteger(body.chainId)||body.chainId<=0))throw new Error('Invalid wallet chain.');const nonce=random(),url=new URL(req.url),expires=Date.now()+300000;const message=createSiweMessage({address:getAddress(body.address),chainId:body.chainId??10143,domain:url.host,uri:url.origin,version:'1',nonce,issuedAt:new Date(),expirationTime:new Date(expires),statement:'Sign in to your private TradeGuard workspace. This does not authorize transactions or token transfers.'});await bucket().put('auth/challenge/'+await key(nonce),JSON.stringify({message,address:getAddress(body.address),expires,origin:url.origin}));return Response.json({message},{headers:{'Set-Cookie':cookie(challengeCookie,nonce,req,300),'Cache-Control':'no-store'}});}
export async function verify(req:Request){originCheck(req);const nonce=cookieValue(req.headers.get('cookie'),challengeCookie);if(!nonce||!/^\w{64}$/.test(nonce))throw new Error('Request a new sign-in message.');const path='auth/challenge/'+await key(nonce),record=await bucket().get(path);if(!record)throw new Error('Sign-in message expired or already used.');const data=await record.json<{message:string;address:Hex;expires:number;origin:string;used?:boolean}>();const body=await req.json() as {message?:string;signature?:Hex};if(data.used||data.expires<Date.now()||data.origin!==new URL(req.url).origin||body.message!==data.message||!body.signature||!/^0x[0-9a-fA-F]{130}$/.test(body.signature)||!await verifyMessage({address:data.address,message:data.message,signature:body.signature}))throw new Error('Invalid or expired wallet signature.');const claimed=await bucket().put(path,JSON.stringify({...data,used:true}),{onlyIf:{etagMatches:record.etag}});if(!claimed)throw new Error('Sign-in message already used.');const token=random();await bucket().put('auth/session/'+await key(token),JSON.stringify({address:data.address,expires:Date.now()+86400000}));const response=Response.json({address:data.address},{headers:{'Cache-Control':'no-store'}});response.headers.append('Set-Cookie',cookie(sessionCookie,token,req,86400));response.headers.append('Set-Cookie',cookie(challengeCookie,'',req,0));return response;}
export async function logout(req:Request){originCheck(req);const token=cookieValue(req.headers.get('cookie'),sessionCookie);if(token&&/^\w{64}$/.test(token))await bucket().put('auth/session/'+await key(token),JSON.stringify({address:'',expires:0}));return Response.json({ok:true},{headers:{'Set-Cookie':cookie(sessionCookie,'',req,0),'Cache-Control':'no-store'}});}
